language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

sudo: false

cache:
    directories:
        - $HOME/.ivy2/cache
        - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

script:
  - sbt fastOptJS

addons:
    apt:
        packages:
            - oracle-java8-installer